### ISSUE TITLE
审核人员退回邮件附带的信息没有在处理人员那里显示

### ISSUE THREAD

**Issue by NExPlain** [qinbingchen/SRFMail_Pro#18]
带信息的退回邮件的信息并没有被显示
![image](https://cloud.githubusercontent.com/assets/4609844/8565582/8e2803f6-2589-11e5-8661-eac470a7453f.png)

**Comment by NExPlain** [comment]
这个问题依然存在.

**Comment by renfeisong** [comment]
这个问题仍旧没有被解决

**Comment by renfeisong** [comment]
solved and closed.
