### ISSUE TITLE
UI 问题汇总（所有关于 UI 的问题在此讨论）

### ISSUE THREAD

**Issue by renfeisong** [qinbingchen/SRFMail_Pro#22]
**第一列**
- 可点击区域鼠标不要用默认的箭头；最好改成`pointer` **WON'T FIX**

**第二列**
- 显示一个区域解释当前列表内邮件的含义，如“所有已被分发但尚未被处理的邮件”
- ~~选中（高亮）区域不对~~
- ~~选中（高亮）后日期仍然是灰色，和蓝色背景对比不明显~~
- 可点击区域鼠标不要用默认的箭头；最好改成`pointer` **WON'T FIX**
- ~~搜索栏去掉（没有实现的功能不要显示 UI ——林老师）（建议可以改成上面提到的列表含义）~~

**第三列**
- ~~上方动作按钮，图标和文字标签要加一些间距~~
- ~~上方动作按钮，要么所有文字都有图标要么都没有（否则给人没做完的感觉）~~
- ~~上方动作按钮，图标不要全都一样（目前图标含义不够清晰）~~
- ~~点击主题标签后的弹出框的位置不对~~
- ~~点击主题标签后的弹出框的文本框含义不明确（建议加 placeholder）~~
- ~~点击提醒后提醒按钮要置灰~~
- ~~点击分发后弹出框的位置不对~~
- ~~点击分发后弹出框的三个文本框含义不明确（不知道各自代表什么含义）~~
- ~~邮件时间对用户不友好（参考 #3 ）~~
- ~~对于回复的邮件，原邮件和回复的邮件区分不明显。建议对第三列进行分区，各区域分界要明显，并用标题清晰地表明每个分区的含义，如：xxx的回复，来自xxx的原始邮件（适当 verbose 一些，对用户友好）~~
- ~~邮件历史~~纪~~记录也需要有标题，建议放在单独分区~~
- ~~顶部要显示当前用户~~姓名~~和身份（参考 #20 ）~~

**Comment by NExPlain** [comment]
分发人员刚登陆时拉主题标签列表拉到的内容为空

**Comment by qinbingchen** [comment]
ALL FIXED.
