### ISSUE TITLE
最晚处理时间格式不对

### ISSUE THREAD

**Issue by renfeisong** [qinbingchen/SRFMail_Pro#36]
如图，`6:27:0`

一个解决方案（来自于湛）

``` javascript
return ('0' + date.getMinutes()).slice(-2)
```

<img width="503" alt="2015-07-09 20 41 59" src="https://cloud.githubusercontent.com/assets/4545784/8595241/fbe1e47e-267a-11e5-96be-11bcb88e9c57.png">

**Comment by qinbingchen** [comment]
Fixed.
