### ISSUE TITLE
分发邮件 UI Bug－选择收件人后会自动出现一个空的收件人

### ISSUE THREAD

**Issue by renfeisong** [qinbingchen/SRFMail_Pro#45]
see the picture below

<img width="302" alt="2015-07-10 02 21 13" src="https://cloud.githubusercontent.com/assets/4545784/8603658/2f3dd9e6-26ac-11e5-8017-9d9fe069bcc2.png">

**Comment by qinbingchen** [comment]
WON‘T FIX.
